/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-06-05 20:18:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.administracion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reportes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tags/parent.tag", Long.valueOf(1490290378000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.8.0-BUILD-SNAPSHOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1479759956000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.8.0-BUILD-SNAPSHOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153399482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_t_005fparent_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("\tactualizarABMReportes();\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    function serviciosAjax() {\n");
      out.write("        $.getJSON('/fielcorresponsal/administration/servicios/json', function(data) {\n");
      out.write("                $.each( data, function(){\n");
      out.write("                    $(\"#select_servicio\").append('<option value=\"'+ this.id +'\">'+ this.nombre +'</option>')\n");
      out.write("                \t})\n");
      out.write("        \t});\n");
      out.write("    }\n");
      out.write("    function agenciasAjax() {\n");
      out.write("        $.getJSON('/fielcorresponsal/administration/agencias/json', function(data) {\n");
      out.write("                $.each( data, function(){\n");
      out.write("                    $(\"#select_agencia\").append('<option value=\"'+ this.id +'\">'+ this.nombre +'</option>')\n");
      out.write("                \t})\n");
      out.write("        \t});\n");
      out.write("    }\n");
      out.write("    function agenciasSucursalesAjax(idAgencia) {\n");
      out.write("        $.getJSON('/fielcorresponsal/administration/agencias/sucursales/json?agenciaId='+idAgencia, function(data) {\n");
      out.write("        \t\t$(\"#select_sucursal\").empty();\n");
      out.write("        \t\t$(\"#select_sucursal\").append('<option value=\"0\" selected>Todas las Sucursales</option>');\n");
      out.write("                $.each( data, function(){\n");
      out.write("                    $(\"#select_sucursal\").append('<option value=\"'+ this.pooNro +'\">'+ this.direccion +'</option>')\n");
      out.write("                \t})\n");
      out.write("        \t});\n");
      out.write("    }\n");
      out.write("    function agenciasTiposAjax() {\n");
      out.write("        $.getJSON('/fielcorresponsal/administration/agencias/tipos/json', function(data) {\n");
      out.write("                $.each( data, function(){\n");
      out.write("                    $(\"#select_tipo\").append('<option value=\"'+ this.value +'\">'+ this.name +'</option>')\n");
      out.write("                \t})\n");
      out.write("        \t});\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    function actualizarABMReportes() {\n");
      out.write("    \tserviciosAjax();\n");
      out.write("    \tagenciasAjax();\n");
      out.write("    \tagenciasTiposAjax();\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$('#abm').on('click', '.icon-pencil', function () {\n");
      out.write("\t\tvar filtro = $(this).attr(\"id\");\n");
      out.write("\t\t$(this).addClass(\"select-btn-pen-enable\");\n");
      out.write("\t\t$('#select_'+filtro).removeClass(\"appearance-none\");\n");
      out.write("\t\t$('#select_'+filtro).prop(\"disabled\", false);\n");
      out.write("\t});\n");
      out.write("\tfunction agregarParametrosYabrirVentana(url){\n");
      out.write("\t\tvar agenciaSelect = document.getElementById(\"select_agencia\");\n");
      out.write("\t\tvar agenciaId = agenciaSelect.options[agenciaSelect.selectedIndex].value;\n");
      out.write("\n");
      out.write("\t\tvar servicioSelect = document.getElementById(\"select_servicio\");\n");
      out.write("\t\tvar servicioId = servicioSelect.options[servicioSelect.selectedIndex].value;\n");
      out.write("\n");
      out.write("\t\tvar agenciaSucursalSelect = document.getElementById(\"select_sucursal\");\n");
      out.write("\t\tvar agenciaSucursalId = agenciaSucursalSelect.options[agenciaSucursalSelect.selectedIndex].value;\n");
      out.write("\n");
      out.write("\t\tvar tipoAgenciaSelect = document.getElementById(\"select_tipo\");\n");
      out.write("\t\tvar tipoAgencia = tipoAgenciaSelect.options[tipoAgenciaSelect.selectedIndex].value;\n");
      out.write("\n");
      out.write("\t\tvar comisionCheck = document.getElementById(\"comisionCNB\");\n");
      out.write("\t\tvar comision = \"\";\n");
      out.write("\t\tif (comisionCheck.checked){\n");
      out.write("\t\t\tcomision = comisionCheck.value;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tvar fechaInicio = document.getElementById(\"fechaDesde\").value;\n");
      out.write("\t\tvar fechaFin = document.getElementById(\"fechaHasta\").value;\n");
      out.write("\n");
      out.write("\t\tif (fechaInicio == null ||fechaInicio ===\"\" ||  fechaFin ==null || fechaFin ===\"\" ){\n");
      out.write("\t\t\t$('#boxMessage').html(message(\"error\", \"La fecha desde y hasta son requeridas.\"));\n");
      out.write("\t\t\t$('#boxMessage').slideDown(300);\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tvar regex = /^(0?[1-9]|[12][0-9]|3[01])[\\/](0?[1-9]|1[012])[\\/]\\d{4}$/;\n");
      out.write("\t\t\tvar regexInicio =fechaInicio.match(regex);\n");
      out.write("\t\t\tvar regexFin =fechaFin.match(regex);\n");
      out.write("\t\t\tif(regexInicio!=null && regexFin!=null ){\n");
      out.write("\t\t\t\t$('#boxMessage').hide();\n");
      out.write("\t\t\t\turl = url + \"?agenciaId=\"+agenciaId+\"&servicioId=\"+servicioId\n");
      out.write("\t\t\t\t+\"&agenciaSucursalId=\"+agenciaSucursalId\n");
      out.write("\t\t\t\t+\"&fechaInicio=\"+fechaInicio+\"&fechaFin=\"+fechaFin\n");
      out.write("\t\t\t\t+\"&tipoAgencia=\"+tipoAgencia+\"&comisionCNB=\"+comision;\n");
      out.write("\t\t\t\twindow.open(url);\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$('#boxMessage').html(message(\"error\", \"El formato de la fecha es incorrecto.\"));\n");
      out.write("\t\t\t\t$('#boxMessage').slideDown(300);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("\t$('#abm').on('click', '#resumenMovAgePdf', function () {\n");
      out.write("\t\tvar url = $(this).data('url');\n");
      out.write("\t\tagregarParametrosYabrirVentana(url);\n");
      out.write("\t});\n");
      out.write("\t$('#abm').on('click', '#listaMovAgePdf', function () {\n");
      out.write("\t\tvar url = $(this).data('url');\n");
      out.write("\t\tagregarParametrosYabrirVentana(url);\n");
      out.write("\t});\n");
      out.write("\t$('#abm').on('click', '#listaMovAgeXlsx', function () {\n");
      out.write("\t\tvar url = $(this).data('url');\n");
      out.write("\t\tagregarParametrosYabrirVentana(url);\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$('#abm').bind(\"DOMSubtreeModified\",function(){\n");
      out.write("\t\tvar fechaIni = $('#fechaDesde').val();\n");
      out.write("\t\tvar fechaFin = $('#fechaHasta').val();\n");
      out.write("\t\tif (fechaIni ===\"\"){\n");
      out.write("\t\t\t$('#fechaDesde').val(fechaActual());\n");
      out.write("\t\t}\n");
      out.write("\t\tif(fechaFin ===\"\"){\n");
      out.write("\t\t\t$('#fechaHasta').val(fechaActual());\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$('#abm').on('change', '#select_agencia', function() {\n");
      out.write("\t    var val = $(\"#select_agencia option:selected\").val();\n");
      out.write("\t    if(val ===\"0\"){\n");
      out.write("\t    \t$(\"#select_sucursal\").empty();\n");
      out.write("    \t\t$(\"#select_sucursal\").append('<option value=\"0\" selected>Todas las Sucursales</option>');\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tagenciasSucursalesAjax(val);\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fparent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:parent
    org.apache.jsp.tag.web.parent_tag _jspx_th_t_005fparent_005f0 = (new org.apache.jsp.tag.web.parent_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_t_005fparent_005f0);
    _jspx_th_t_005fparent_005f0.setJspContext(_jspx_page_context);
    _jspx_th_t_005fparent_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_t_005fparent_005f0, null));
    _jspx_th_t_005fparent_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_t_005fparent_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/administracion/reportes.jsp(117,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/administration");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\">\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdl-0\">\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdl-0\">\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-6 title-page\">\n");
      out.write("\t\t\t\t\t<h2>Administración<span class=\"glyphicon glyphicon-menu-right\"></span>Reportes</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-6 pdr-0\">\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\">\n");
      out.write("\t\t\t<hr class=\"line-blue\">\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div id=\"abm\">\n");
      out.write("\t\t<h3 class=\"tipo-seguro\">ABM de Reportes</h3>\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\" id=\"boxMessage\" style=\"display: none;\">\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERROR}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hasError\">\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WARNING}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hasWarning\">\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12  pdr-1 caja-blanca-rellena\">\n");
      out.write("\t\t\t<div class=\"row mb-10\">\n");
      out.write("\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\">Servicios:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
      out.write("\t\t\t\t\t<select class=\"col-xs-4 col-sm-4 col-md-4 col-lg-3 input-pen-without-appearance appearance-none input-pen-tipDoc form-control input-form-seguro \" id=\"select_servicio\" disabled>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected>Todos los Servicios</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t<span data-toggle=\"tooltip\" title=\"Cambiar Servicio.\" class=\"icon-pencil select-btn-pen\" style=\"font-size: 100%;margin-left: 0px; margin-right: 0px;}\" id=\"servicio\"></span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<label class=\" col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\">Agencias:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
      out.write("\t\t\t\t\t<select class=\"col-xs-4 col-sm-4 col-md-4 col-lg-3 input-pen-without-appearance appearance-none input-pen-tipDoc form-control input-form-seguro \" id=\"select_agencia\" disabled>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected>Todas las Agencias</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t<span data-toggle=\"tooltip\" title=\"Cambiar Agencia.\" class=\"icon-pencil select-btn-pen\" style=\"font-size: 100%;margin-left: 0px; margin-right: 0px;}\" id=\"agencia\"></span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<label class=\" col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\">Sucursales:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0 pdlr-10\">\n");
      out.write("\t\t\t\t\t<select class=\"col-xs-4 col-sm-4 col-md-4 col-lg-3 input-pen-without-appearance appearance-none input-pen-tipDoc form-control input-form-seguro \" id=\"select_sucursal\" disabled>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected>Todas las Sucursales</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t<span data-toggle=\"tooltip\" title=\"Cambiar Sucursal.\" class=\"icon-pencil select-btn-pen\" style=\"font-size: 100%;margin-left: 0px; margin-right: 0px;}\" id=\"sucursal\"></span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\" row mb-10\">\n");
      out.write("\t\t\t\t<label class=\" col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\">Fecha Desde:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-2 pdl-0\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<input id=\"fechaDesde\" type=\"text\" value=\"\" class=\"form-control input-form-seguro dateImput\" placeholder=\"dd/mm/aaaa\" title=\"Formato de fecha: dia/mes/aï¿½o.\" pattern=\"dd/MM/yyyy\" onkeyup=\"this.value=this.value.replace(/^(\\d\\d)(\\d)$/g,'$1/$2').replace(/^(\\d\\d\\/\\d\\d)(\\d+)$/g,'$1/$2').replace(/[^\\d\\/]/g,'')\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<label class=\" col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\">Fecha Hasta:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-2 pdl-0\">\n");
      out.write("\t\t\t\t\t<input id=\"fechaHasta\"  type=\"text\" value=\"\" class=\"form-control input-form-seguro dateImput\"  placeholder=\"dd/mm/aaaa\" title=\"Formato de fecha: dia/mes/aï¿½o.\" pattern=\"dd/MM/yyyy\" onkeyup=\"this.value=this.value.replace(/^(\\d\\d)(\\d)$/g,'$1/$2').replace(/^(\\d\\d\\/\\d\\d)(\\d+)$/g,'$1/$2').replace(/[^\\d\\/]/g,'')\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<label class=\" col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\">Tipo:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
      out.write("\t\t\t\t\t<select class=\"col-xs-4 col-sm-4 col-md-4 col-lg-3 input-pen-without-appearance appearance-none input-pen-tipDoc form-control input-form-seguro \" id=\"select_tipo\" disabled>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected>Todos los Tipos de Agencia</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t<span data-toggle=\"tooltip\" title=\"Cambiar Tipo Agencia.\" class=\"icon-pencil select-btn-pen\" style=\"font-size: 100%;margin-left: 0px; margin-right: 0px;}\" id=\"tipo\"></span>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<label class=\" col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0 text-right label-form-seguro\" for=\"comisionCNB\">Comisión:</label>\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-1 pdl-0\">\n");
      out.write("\t\t\t\t\t<input id=\"comisionCNB\"  type=\"checkbox\" class=\"form-control input-form-seguro \" value=\"S\" checked=\"checked\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\">\n");
      out.write("\n");
      out.write("            <table class=\"table\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr class=\"label-blue\">\n");
      out.write("                            <th class=\"text-center\">Reporte</th>\n");
      out.write("                            <th class=\"text-center\">Acción</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"text-center\">Resumen de Movimientos de CNB</td>\n");
      out.write("                        <td class=\"text-center\">\n");
      out.write("                            <i id=\"resumenMovAgePdf\" data-url=\"/fielcorresponsal/administration/reportes/agencias/movimientos/resumen/pdf\" data-toggle=\"tooltip\" title=\"Formato PDF\" class=\"fa fa-file-pdf-o\" style=\"font-size:20px;color:red;\"></i>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"text-center\">Listado de Movimientos de CNB</td>\n");
      out.write("                        <td class=\"text-center\">\n");
      out.write("                            <i id=\"listaMovAgePdf\" data-url=\"/fielcorresponsal/administration/reportes/agencias/movimientos/pdf\" data-toggle=\"tooltip\" title=\"Formato PDF\" class=\"fa fa-file-pdf-o\" style=\"font-size:20px;color:red;\"></i>\n");
      out.write("                            <i id=\"listaMovAgeXlsx\"  data-url=\"/fielcorresponsal/administration/reportes/agencias/movimientos/xlsx\" data-toggle=\"tooltip\" title=\"Formato Excel\" class=\"fa fa-file-excel-o\" style=\"font-size:20px;color:green;\"></i>\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12  pdr-0\">\n");
      out.write("\t\t<div class=\"col-xs-3 col-sm-3 col-md-2 col-lg-2 pdlr-0 link-previous\">\n");
      out.write("\t\t\t<a class=\"linkSeguroHome\" href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("'><span class=\"glyphicon glyphicon-chevron-left\"></span><span>Administración</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
