/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-09-27 16:09:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.administracion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class proceso_005fliquidacion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/tags/parent.tag", Long.valueOf(1503344394000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.12.0-RC1/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.1.RELEASE.jar", Long.valueOf(1479760400000L));
    _jspx_dependants.put("/WEB-INF/custom-funcions.tld", Long.valueOf(1503344394000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1479759956000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.12.0-RC1/WEB-INF/lib/spring-webmvc-3.2.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1359028012000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.12.0-RC1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fid_005fcssErrorClass_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005foption_0026_005fvalue_005fLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fid_005fcssErrorClass_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005foption_0026_005fvalue_005fLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fid_005fcssErrorClass_005fclass.release();
    _005fjspx_005ftagPool_005fsf_005foption_0026_005fvalue_005fLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin.release();
    _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  t:parent
      org.apache.jsp.tag.web.parent_tag _jspx_th_t_005fparent_005f0 = (new org.apache.jsp.tag.web.parent_tag());
      _jsp_getInstanceManager().newInstance(_jspx_th_t_005fparent_005f0);
      _jspx_th_t_005fparent_005f0.setJspContext(_jspx_page_context);
      _jspx_th_t_005fparent_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_t_005fparent_005f0, null));
      _jspx_th_t_005fparent_005f0.doTag();
      _jsp_getInstanceManager().destroyInstance(_jspx_th_t_005fparent_005f0);
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t    $('#tAgencias').DataTable({\n");
      out.write("\t    \tlengthMenu: [ 5, 10, 25, 50 ],\n");
      out.write("\t        language: {\n");
      out.write("\t            url: '/fielcorresponsal/resources/i18n/es_ES.json'\n");
      out.write("\t        }\n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t    $('#tServicios').DataTable({\n");
      out.write("\t    \tlengthMenu: [ 5, 10, 25, 50 ],\n");
      out.write("\t        language: {\n");
      out.write("\t            url: '/fielcorresponsal/resources/i18n/es_ES.json'\n");
      out.write("\t        }\n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t    $(\"#fecha\").datepicker({\n");
      out.write("\t\t\tlanguage: 'es',\n");
      out.write("\t\t\torientation:'bottom right',\n");
      out.write("\t\t\ttodayHighlight: true\n");
      out.write("\t\t});\n");
      out.write("\t    \n");
      out.write("\t    $('#tAgencias tbody tr').on( 'click', 'input[type=checkbox]', function () {\n");
      out.write("\t        $(this.parentElement.parentElement).toggleClass('selected');\n");
      out.write("\t    } );\n");
      out.write("\t    \n");
      out.write("\t    $('#tServicios tbody tr').on( 'click', 'input[type=checkbox]', function () {\n");
      out.write("\t        $(this.parentElement.parentElement).toggleClass('selected');\n");
      out.write("\t    } );\n");
      out.write("\n");
      out.write("\t    activeHeader(\"adminPage\");\n");
      out.write("\t\tmayusculas();\n");
      out.write("\t\t$('#myModalReading').modal('hide');\n");
      out.write("\t    $(\"#btn-agencia\").click(function(){\n");
      out.write("\t        $(\"#agenciasModal\").modal();\n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t    $(\"#btn-servicio\").click(function(){\n");
      out.write("\t        $(\"#serviciosModal\").modal();\n");
      out.write("\t    });\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t//Agencia\n");
      out.write("    function cancelAgenciaModal(){\n");
      out.write("    \t\n");
      out.write("    \tvar tabla = $('#tAgencias').DataTable();\n");
      out.write("\t\ttabla.rows('.selected').$('input[type=checkbox]').prop(\"checked\", false);\n");
      out.write("\t\ttabla.rows('.selected').$('tr').removeClass('selected');\n");
      out.write("    \t$(\"#agencia\").val('');\n");
      out.write("    }\n");
      out.write("    function confirmAgenciaModal(){\n");
      out.write("    \t\n");
      out.write("    \tvar tabla = $('#tAgencias').DataTable();\n");
      out.write("        $(\"#agencia\").val( tabla.rows('.selected').data().length +' agencia(s) seleccionada(s)');\n");
      out.write("\n");
      out.write("        var seleccionados=[];\n");
      out.write("       \tvar count=0;\n");
      out.write("        tabla.rows('.selected').every(function(index) { \n");
      out.write("        \tconsole.log($(this.node()).find('input')[0].value);\n");
      out.write("        \tseleccionados[count]=$(this.node()).find('input')[0].value;\n");
      out.write("        \tcount++;\n");
      out.write("        });\n");
      out.write("\t    document.forms[\"myForm\"][\"agenciasSeleccionadas\"].value = seleccionados;\n");
      out.write("\t    console.log(seleccionados)\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    //Servicios\n");
      out.write("\tfunction cancelServicioModal(){\n");
      out.write("    \t\n");
      out.write("    \tvar tabla = $('#tServicios').DataTable();\n");
      out.write("\t\ttabla.rows('.selected').$('input[type=checkbox]').prop(\"checked\", false);\n");
      out.write("\t\ttabla.rows('.selected').$('tr').removeClass('selected');\n");
      out.write("    \t$(\"#servicio\").val('');\n");
      out.write("    }\n");
      out.write("    function confirmServicioModal(){\n");
      out.write("    \tvar tabla = $('#tServicios').DataTable();\n");
      out.write("        $(\"#servicio\").val( tabla.rows('.selected').data().length +' servicio(s) seleccionado(s)');\n");
      out.write("        \n");
      out.write("        var seleccionados=[];\n");
      out.write("       \tvar count=0;\n");
      out.write("        tabla.rows('.selected').every(function(index) { \n");
      out.write("        \tconsole.log($(this.node()).find('input')[0].value);\n");
      out.write("        \tseleccionados[count]=$(this.node()).find('input')[0].value;\n");
      out.write("        \tcount++;\n");
      out.write("        });\n");
      out.write("\t    document.forms[\"myForm\"][\"serviciosSeleccionados\"].value = seleccionados;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("\tfunction validateForm() {\n");
      out.write("\t\tvar error = \"\";\n");
      out.write("\t    var fecha = document.forms[\"myForm\"][\"fecha\"].value;\n");
      out.write("\t    fecha = fecha.trim();\n");
      out.write("\n");
      out.write("\t    if (fecha == \"\") {\n");
      out.write("\t\t\terror = error + \"<li>Debe ingresar una fecha.</li>\"\n");
      out.write("\t    }\n");
      out.write("\t    document.forms[\"myForm\"][\"fecha\"].value = fecha;\n");
      out.write("        \t \t    \n");
      out.write("\t    if(error !=\"\"){\n");
      out.write("\t\t    error = \"<ul>\"+error+\"</ul>\";\n");
      out.write("\t    \t$('#boxMessage').html(messageWithIcon(\"error\", \"Debe completar los campos solicitados\", error));\n");
      out.write("\t\t\t$('#boxMessage').slideDown(300);\n");
      out.write("\t        return false;\n");
      out.write("\t    }\n");
      out.write("\t    $('#myModalReading').modal('show');\n");
      out.write("\t    return true;\n");
      out.write("\t}\n");
      out.write("    \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".modal-body {\n");
      out.write("    height: 360px;\n");
      out.write("}\n");
      out.write(".btn-selection{\n");
      out.write("\tbackground-color: #00348F;\n");
      out.write("\tcolor: white;\n");
      out.write("\tpadding: 5px;\n");
      out.write("\tborder-radius: 10px;\n");
      out.write("\tborder: 2px solid #00348F;\n");
      out.write("}\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sf_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_sf_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fsf_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    try {
      _jspx_th_sf_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fselect_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(54,7) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${viewModel.monedas}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(54,7) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005foptions_005f0.setItemValue("codigo");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(54,7) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005foptions_005f0.setItemLabel("nombre");
      int[] _jspx_push_body_count_sf_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005foptions_005f0 = _jspx_th_sf_005foptions_005f0.doStartTag();
        if (_jspx_th_sf_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005foptions_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_sf_005foptions_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(71,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setPath("fecha");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(71,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setId("fecha");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(71,7) null
      _jspx_th_sf_005finput_005f0.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(71,7) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setCssErrorClass(" form-control input-form-seguro");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(71,7) null
      _jspx_th_sf_005finput_005f0.setDynamicAttribute(null, "class", "form-control input-form-seguro");
      int[] _jspx_push_body_count_sf_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f0 = _jspx_th_sf_005finput_005f0.doStartTag();
        if (_jspx_th_sf_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_sf_005fhidden_005f0 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    try {
      _jspx_th_sf_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(82,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fhidden_005f0.setPath("agenciasSeleccionadas");
      int[] _jspx_push_body_count_sf_005fhidden_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fhidden_005f0 = _jspx_th_sf_005fhidden_005f0.doStartTag();
        if (_jspx_th_sf_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fhidden_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fhidden_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fhidden_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fhidden_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fhidden_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_sf_005fhidden_005f1 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    try {
      _jspx_th_sf_005fhidden_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fhidden_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(83,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fhidden_005f1.setPath("serviciosSeleccionados");
      int[] _jspx_push_body_count_sf_005fhidden_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fhidden_005f1 = _jspx_th_sf_005fhidden_005f1.doStartTag();
        if (_jspx_th_sf_005fhidden_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fhidden_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fhidden_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fhidden_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fhidden_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(109,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/administracion/proceso_liquidacion.jsp(109,10) '${viewModel.agencias}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${viewModel.agencias}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(109,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("agencia");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(109,10) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(109,10) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${agencia.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            if (_jspx_meth_sf_005fhidden_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${agencia.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            if (_jspx_meth_sf_005fhidden_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"10%\">");
            if (_jspx_meth_sf_005fcheckbox_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fhidden_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_sf_005fhidden_005f2 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    try {
      _jspx_th_sf_005fhidden_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fhidden_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(111,29) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fhidden_005f2.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("agencias[${status.index}].id", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sf_005fhidden_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fhidden_005f2 = _jspx_th_sf_005fhidden_005f2.doStartTag();
        if (_jspx_th_sf_005fhidden_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fhidden_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fhidden_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fhidden_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fhidden_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fhidden_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_sf_005fhidden_005f3 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    try {
      _jspx_th_sf_005fhidden_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fhidden_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(112,33) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fhidden_005f3.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("agencias[${status.index}].nombre", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sf_005fhidden_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fhidden_005f3 = _jspx_th_sf_005fhidden_005f3.doStartTag();
        if (_jspx_th_sf_005fhidden_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fhidden_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fhidden_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fhidden_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fhidden_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fcheckbox_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_sf_005fcheckbox_005f0 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    try {
      _jspx_th_sf_005fcheckbox_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fcheckbox_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(113,28) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fcheckbox_005f0.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("agencias[${status.index}].checked", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sf_005fcheckbox_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fcheckbox_005f0 = _jspx_th_sf_005fcheckbox_005f0.doStartTag();
        if (_jspx_th_sf_005fcheckbox_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fcheckbox_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fcheckbox_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fcheckbox_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fcheckbox_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(157,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/administracion/proceso_liquidacion.jsp(157,10) '${viewModel.servicios}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${viewModel.servicios}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(157,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("servicio");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(157,10) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(157,10) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(0);
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${servicio.serviciosId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            if (_jspx_meth_sf_005fhidden_005f4(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${servicio.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            if (_jspx_meth_sf_005fhidden_005f5(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"10%\">");
            if (_jspx_meth_sf_005fcheckbox_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fhidden_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_sf_005fhidden_005f4 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    try {
      _jspx_th_sf_005fhidden_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fhidden_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(159,39) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fhidden_005f4.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("servicios[${status.index}].serviciosId", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sf_005fhidden_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fhidden_005f4 = _jspx_th_sf_005fhidden_005f4.doStartTag();
        if (_jspx_th_sf_005fhidden_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fhidden_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fhidden_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fhidden_005f4.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fhidden_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fhidden_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_sf_005fhidden_005f5 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    try {
      _jspx_th_sf_005fhidden_005f5.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fhidden_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(160,34) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fhidden_005f5.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("servicios[${status.index}].nombre", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sf_005fhidden_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fhidden_005f5 = _jspx_th_sf_005fhidden_005f5.doStartTag();
        if (_jspx_th_sf_005fhidden_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fhidden_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fhidden_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fhidden_005f5.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fhidden_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005fcheckbox_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_sf_005fcheckbox_005f1 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    try {
      _jspx_th_sf_005fcheckbox_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fcheckbox_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(161,28) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fcheckbox_005f1.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("servicios[${status.index}].checked", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_sf_005fcheckbox_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fcheckbox_005f1 = _jspx_th_sf_005fcheckbox_005f1.doStartTag();
        if (_jspx_th_sf_005fcheckbox_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fcheckbox_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fcheckbox_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fcheckbox_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fcheckbox_0026_005fpath_005fnobody.reuse(_jspx_th_sf_005fcheckbox_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/administracion/proceso_liquidacion.jsp(187,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/administration/procesos");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public void invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\">\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdl-0\">\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdl-0\">\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-12 title-page\">\n");
      out.write("\t\t\t\t\t<h2>Administración<span class=\"glyphicon glyphicon-menu-right\"></span>Proceso Liquidación</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-6 pdr-0\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div> \t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\">\n");
      out.write("\t\t\t<hr class=\"line-blue\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div id=\"list\">\t\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\" id=\"boxMessage\" style=\"display: none;\">\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERROR}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hasError\">\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WARNING}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hasWarning\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
      //  sf:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_sf_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      try {
        _jspx_th_sf_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_sf_005fform_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(34,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sf_005fform_005f0.setMethod("POST");
        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(34,2) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sf_005fform_005f0.setCommandName("viewModel");
        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(34,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sf_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/administration/liquidacion/procesar", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(34,2) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sf_005fform_005f0.setName("myForm");
        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(34,2) name = onsubmit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_sf_005fform_005f0.setOnsubmit("return validateForm()");
        int[] _jspx_push_body_count_sf_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_sf_005fform_005f0 = _jspx_th_sf_005fform_005f0.doStartTag();
          if (_jspx_eval_sf_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("\t\t\t<div\n");
              out.write("\t\t\t\tclass=\"col-xs-12 col-sm-12 col-md-12 col-lg-12  pdr-1 caja-blanca-rellena\">\n");
              out.write("\n");
              out.write("\t\t\t\t<div class=\"mb-10 step-two-title\">\n");
              out.write("\t\t\t\t\t<h3>Parámetros</h3>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\t\t\t\t<div class=\"row mb-10\">\n");
              out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\" for=\"agencia\">Agencia:</label>\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
              out.write("\t\t\t\t\t\t<input id=\"agencia\" type=\"text\" class=\"form-control input-form-seguro\" disabled=\"disabled\" placeholder=\"Todos\"/>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-1 col-lg-1 pdl-0\">\n");
              out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-selection\" id=\"btn-agencia\">Seleccionar</button>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\n");
              out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\" for=\"moneda\">Moneda:</label>\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
              out.write("\t\t\t\t\t\t");
              //  sf:select
              org.springframework.web.servlet.tags.form.SelectTag _jspx_th_sf_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fid_005fcssErrorClass_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
              try {
                _jspx_th_sf_005fselect_005f0.setPageContext(_jspx_page_context);
                _jspx_th_sf_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
                // /WEB-INF/views/administracion/proceso_liquidacion.jsp(52,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sf_005fselect_005f0.setPath("moneda");
                // /WEB-INF/views/administracion/proceso_liquidacion.jsp(52,6) null
                _jspx_th_sf_005fselect_005f0.setDynamicAttribute(null, "class", "form-control input-form-seguro");
                // /WEB-INF/views/administracion/proceso_liquidacion.jsp(52,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sf_005fselect_005f0.setId("moneda");
                // /WEB-INF/views/administracion/proceso_liquidacion.jsp(52,6) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_sf_005fselect_005f0.setCssErrorClass("error-input");
                int[] _jspx_push_body_count_sf_005fselect_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_sf_005fselect_005f0 = _jspx_th_sf_005fselect_005f0.doStartTag();
                  if (_jspx_eval_sf_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    do {
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t");
                      //  sf:option
                      org.springframework.web.servlet.tags.form.OptionTag _jspx_th_sf_005foption_005f0 = (org.springframework.web.servlet.tags.form.OptionTag) _005fjspx_005ftagPool_005fsf_005foption_0026_005fvalue_005fLabel_005fnobody.get(org.springframework.web.servlet.tags.form.OptionTag.class);
                      try {
                        _jspx_th_sf_005foption_005f0.setPageContext(_jspx_page_context);
                        _jspx_th_sf_005foption_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fselect_005f0);
                        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(53,7) null
                        _jspx_th_sf_005foption_005f0.setDynamicAttribute(null, "Label", "Todos");
                        // /WEB-INF/views/administracion/proceso_liquidacion.jsp(53,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                        _jspx_th_sf_005foption_005f0.setValue("");
                        int[] _jspx_push_body_count_sf_005foption_005f0 = new int[] { 0 };
                        try {
                          int _jspx_eval_sf_005foption_005f0 = _jspx_th_sf_005foption_005f0.doStartTag();
                          if (_jspx_th_sf_005foption_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            throw new javax.servlet.jsp.SkipPageException();
                          }
                        } catch (java.lang.Throwable _jspx_exception) {
                          while (_jspx_push_body_count_sf_005foption_005f0[0]-- > 0)
                            out = _jspx_page_context.popBody();
                          _jspx_th_sf_005foption_005f0.doCatch(_jspx_exception);
                        } finally {
                          _jspx_th_sf_005foption_005f0.doFinally();
                        }
                      } finally {
                        _005fjspx_005ftagPool_005fsf_005foption_0026_005fvalue_005fLabel_005fnobody.reuse(_jspx_th_sf_005foption_005f0);
                      }
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t");
                      if (_jspx_meth_sf_005foptions_005f0(_jspx_th_sf_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fselect_005f0))
                        return;
                      out.write("\n");
                      out.write("\t\t\t\t\t\t");
                      int evalDoAfterBody = _jspx_th_sf_005fselect_005f0.doAfterBody();
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                  }
                  if (_jspx_th_sf_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    throw new javax.servlet.jsp.SkipPageException();
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_sf_005fselect_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_sf_005fselect_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_sf_005fselect_005f0.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fsf_005fselect_0026_005fpath_005fid_005fcssErrorClass_005fclass.reuse(_jspx_th_sf_005fselect_005f0);
              }
              out.write("\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\n");
              out.write("\t\t\t\t<div class=\"row mb-10\">\n");
              out.write("\t\t\t\t\n");
              out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\" for=\"servicio\">Servicio:</label>\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
              out.write("\t\t\t\t\t\t<input id=\"servicio\" type=\"text\" class=\"form-control input-form-seguro\" disabled=\"disabled\" placeholder=\"Todos\"/>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-1 col-lg-1 pdl-0\">\n");
              out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-selection\" id=\"btn-servicio\">Seleccionar</button>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\n");
              out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\" for=\"fecha\">Fecha:</label>\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
              out.write("\t\t\t\t\t\t ");
              if (_jspx_meth_sf_005finput_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
                return;
              out.write("\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\n");
              out.write("\t\t\t\t<div class=\"row mb-10\">\n");
              out.write("\t\t\t\t\t<div class=\"col-xs-8 col-sm-6 col-md-5 col-lg-4 pull-right\">\n");
              out.write("\t\t\t\t\t\t<button type=\"submit\" id=\"btn-confirmar\" class=\"btn-next-blue\">Procesar</button>\n");
              out.write("\t\t\t\t\t\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\n");
              out.write("\t\t\t\t");
              if (_jspx_meth_sf_005fhidden_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
                return;
              out.write("\n");
              out.write("\t\t\t\t");
              if (_jspx_meth_sf_005fhidden_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
                return;
              out.write("\n");
              out.write("\t\t\t</div>\n");
              out.write("\t\t\t\n");
              out.write("\t\t\t<!-- Modal Agencia-->\n");
              out.write("\t\t\t<div class=\"modal fade\" id=\"agenciasModal\" role=\"dialog\">\n");
              out.write("\t\t\t\t<div class=\"modal-dialog\">\n");
              out.write("\t\t\n");
              out.write("\t\t\t\t\t<!-- Modal content -->\n");
              out.write("\t\t\t\t\t<div class=\"modal-content\">\n");
              out.write("\t\t\t\t\t\t<div class=\"modal-header title-page\">\n");
              out.write("\t\t\t\t\t\t\t<h4>\n");
              out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-calendar\"></span> Agencias\n");
              out.write("\t\t\t\t\t\t\t</h4>\n");
              out.write("\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t<div class=\"modal-body\">\n");
              out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 \">\n");
              out.write("\t\t\t\t\t\t\t\t<table id=\"tAgencias\" class=\"table table-hover display\">\n");
              out.write("\t\t\t\t\t\t\t\t\t<thead>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<th>ID</th>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Nombre</th>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Seleccionado</th>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
              out.write("\t\t\t\t\t\t\t\t\t</thead>\n");
              out.write("\t\t\t\t\t\t\t\t\t\n");
              out.write("\t\t\t\t\t\t\t\t\t<tbody>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_c_005fforEach_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
                return;
              out.write("\n");
              out.write("\t\t\t\t\t\t\t\t\t</tbody>\n");
              out.write("\t\t\t\t\t\t\t\t</table>\n");
              out.write("\t\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\n");
              out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn-next-blue pull-right\"\n");
              out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\" onclick=\"cancelAgenciaModal()\">\n");
              out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span> Limpiar\n");
              out.write("\t\t\t\t\t\t\t</button>\n");
              out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn-next-blue pull-right\"\n");
              out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\"  onclick=\"confirmAgenciaModal()\">\n");
              out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-ok\"></span> Confirmar\n");
              out.write("\t\t\t\t\t\t\t</button>\n");
              out.write("\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\t\t\t</div>\n");
              out.write("\t\t\t\n");
              out.write("\t\t\t<!-- Modal Servicio-->\n");
              out.write("\t\t\t<div class=\"modal fade\" id=\"serviciosModal\" role=\"dialog\">\n");
              out.write("\t\t\t\t<div class=\"modal-dialog\">\n");
              out.write("\t\t\n");
              out.write("\t\t\t\t\t<!-- Modal content -->\n");
              out.write("\t\t\t\t\t<div class=\"modal-content\">\n");
              out.write("\t\t\t\t\t\t<div class=\"modal-header title-page\">\n");
              out.write("\t\t\t\t\t\t\t<h4>\n");
              out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-th-list\"></span> Servicios\n");
              out.write("\t\t\t\t\t\t\t</h4>\n");
              out.write("\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t<div class=\"modal-body\">\n");
              out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 \">\n");
              out.write("\t\t\t\t\t\t\t\t<table id=\"tServicios\" class=\"table table-hover display\">\n");
              out.write("\t\t\t\t\t\t\t\t\t<thead>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<th>ID</th>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Nombre</th>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Seleccionado</th>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
              out.write("\t\t\t\t\t\t\t\t\t</thead>\n");
              out.write("\t\t\t\t\t\t\t\t\t\n");
              out.write("\t\t\t\t\t\t\t\t\t<tbody>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_c_005fforEach_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
                return;
              out.write("\n");
              out.write("\t\t\t\t\t\t\t\t\t</tbody>\n");
              out.write("\t\t\t\t\t\t\t\t</table>\n");
              out.write("\t\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\n");
              out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn-next-blue pull-right\"\n");
              out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\" onclick=\"cancelServicioModal()\">\n");
              out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\"></span> Limpiar\n");
              out.write("\t\t\t\t\t\t\t</button>\n");
              out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn-next-blue pull-right\"\n");
              out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\" onclick=\"confirmServicioModal()\">\n");
              out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-ok\"></span> Confirmar\n");
              out.write("\t\t\t\t\t\t\t</button>\n");
              out.write("\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\t\t\t</div>\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_sf_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_sf_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            throw new javax.servlet.jsp.SkipPageException();
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_sf_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_sf_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_sf_005fform_005f0.doFinally();
        }
      } finally {
        _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_sf_005fform_005f0);
      }
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12  pdr-0\">\n");
      out.write("\t\t<div class=\"col-xs-3 col-sm-3 col-md-2 col-lg-2 pdlr-0 link-previous\">\n");
      out.write("\t\t\t<a class=\"linkSeguroHome\" href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("'><span class=\"glyphicon glyphicon-chevron-left\"></span><span>Procesos</span></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal fade\" id=\"myModalReading\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" data-backdrop=\"static\"\n");
      out.write("\t\tdata-keyboard=\"false\">\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t<div class=\"\" style=\"padding-top: 200px;\">\n");
      out.write("\t\t\t\t<div class=\"modal-loading\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      return;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
