/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-07-11 12:47:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.extracciones;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class solicitar_005fdatos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.9.0-SNAPSHOT/WEB-INF/lib/spring-webmvc-3.2.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1359028012000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.9.0-SNAPSHOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/tags/parent.tag", Long.valueOf(1498675530000L));
    _jspx_dependants.put("jar:file:/home/oem/Programas/apache-tomcat-8.5.6/webapps/fielcorresponsal%23%231.9.0-SNAPSHOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.1.RELEASE.jar", Long.valueOf(1479760400000L));
    _jspx_dependants.put("/WEB-INF/custom-funcions.tld", Long.valueOf(1490290378000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1479759956000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody.release();
    _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_t_005fparent_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"myModalReading\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" data-backdrop=\"static\" data-keyboard=\"false\">\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    <div class=\"\" style=\"padding-top: 200px;\">\n");
      out.write("      <div class=\"modal-loading\">\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tactiveHeader(\"withdrawPage\");\n");
      out.write("\t\tmayusculas();\n");
      out.write("\t\tcheckError();\n");
      out.write("\t\tcheckWarning();\n");
      out.write("\t\tsetDocTipeValue();\n");
      out.write("\t\tsetOrigDocValue();\n");
      out.write("\t\t$('#myModalReading').modal('hide');\n");
      out.write("\t\t$(\"#fechaNacimiento\").datepicker({\n");
      out.write("\t\t\tlanguage: 'es',\n");
      out.write("\t\t\torientation:'bottom right',\n");
      out.write("\t\t\ttodayHighlight: true\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\tfunction checkError(){\n");
      out.write("\t\tvar val = $(\"#hasError\").val();\n");
      out.write("\t\tif(val) {\n");
      out.write("\t\t\t$('#boxMessage').html(message(\"error\", val));\n");
      out.write("\t\t\t$('#boxMessage').slideDown(300);\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("\tfunction checkWarning(){\n");
      out.write("\t\tvar val = $(\"#hasWarning\").val();\n");
      out.write("\t\tif(val) {\n");
      out.write("\t\t\t$('#boxMessage').html(message(\"warning\", val));\n");
      out.write("\t\t\t$('#boxMessage').slideDown(300);\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("\tfunction setDocTipeValue(){\n");
      out.write("\t\tvar val = $(\"#select_client_tipeDoc\").val();\n");
      out.write("\t\tif(val == null || val == \"\"){\n");
      out.write("\t\t\t$(\"#select_client_tipeDoc\").val('2');\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$(\"#select_client_tipeDoc\").val(val);\n");
      out.write("\t\t\t$('#select_client_tipeDoc').prop(\"disabled\", true);\n");
      out.write("\t\t}\t\t\n");
      out.write("\t};\n");
      out.write("\tfunction setOrigDocValue(){\n");
      out.write("\t\tvar val = $(\"#select_client_origDoc\").val();\n");
      out.write("\t\tif(val == null || val == \"\"){\n");
      out.write("\t\t\t$(\"#select_client_origDoc\").val('600');\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$(\"#select_client_origDoc\").val(val);\n");
      out.write("\t\t\t$('#select_client_origDoc').prop(\"disabled\", true);\n");
      out.write("\t\t}\t\t\n");
      out.write("\t};\n");
      out.write("\t$('#select_client_tipeDoc').on('change', function(){\n");
      out.write("\t\tvar tipo_doc = $(\"#select_client_tipeDoc\").children(':selected').val();\n");
      out.write("\t\t$(\"#client_tipeDoc_value\").val(tipo_doc);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tfunction validateForm() {\n");
      out.write("\t\tvar error = \"\";\n");
      out.write("\t    var nrodoc = document.forms[\"myForm\"][\"numeroDocumento\"].value;\n");
      out.write("\t    nrodoc = nrodoc.trim();\n");
      out.write("\t    var tipoDoc = document.forms[\"myForm\"][\"select_client_tipeDoc\"].value;\n");
      out.write("\t    var pais = document.forms[\"myForm\"][\"select_client_origDoc\"].value;\n");
      out.write("\t    var fechaNacimiento = document.forms[\"myForm\"][\"fechaNacimiento\"].value;\n");
      out.write("\t    fechaNacimiento = fechaNacimiento.trim();\n");
      out.write("\t    var telefonoCelular = document.forms[\"myForm\"][\"telefonoCelular\"].value;\n");
      out.write("\t    telefonoCelular = telefonoCelular.trim();\n");
      out.write("\n");
      out.write("\t\tif(nrodoc === \"\"){\n");
      out.write("\t\t\terror = error + \"<li>Debe ingresar el Nro. de documento.</li>\"\n");
      out.write("\t\t}\n");
      out.write("\t    document.forms[\"myForm\"][\"numeroDocumento\"].value = nrodoc;\n");
      out.write("\t    \n");
      out.write("\t    if (tipoDoc == \"\") {\n");
      out.write("\t\t\terror = error + \"<li>Debe seleccionar el tipo de documento.</li>\"\n");
      out.write("\t    }\n");
      out.write("\t    \n");
      out.write("\t    if (pais == \"\") {\n");
      out.write("\t\t\terror = error + \"<li>Debe seleccionar el país de origen de tipo de documento.</li>\"\n");
      out.write("\t    }\n");
      out.write("\t    \n");
      out.write("\t    if(fechaNacimiento === \"\"){\n");
      out.write("\t\t\terror = error + \"<li>Debe ingresar la Fecha de Nacimiento.</li>\"\n");
      out.write("\t\t}\n");
      out.write("\t    document.forms[\"myForm\"][\"fechaNacimiento\"].value = fechaNacimiento;\n");
      out.write("\t    \n");
      out.write("\t    if(telefonoCelular === \"\"){\n");
      out.write("\t\t\terror = error + \"<li>Debe ingresar el Telefono Celular.</li>\"\n");
      out.write("\t\t}\n");
      out.write("\t    document.forms[\"myForm\"][\"telefonoCelular\"].value = telefonoCelular;\n");
      out.write("\t    \n");
      out.write("\t    if(error !=\"\"){\n");
      out.write("\t\t    error = \"<ul>\"+error+\"</ul>\";\n");
      out.write("\t    \t$('#boxMessage').html(message(\"error\", error));\n");
      out.write("\t\t\t$('#boxMessage').slideDown(300);\n");
      out.write("\t        return false;\n");
      out.write("\t    }\n");
      out.write("\t    $('#myModalReading').modal('show');\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("formatoFecha");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/extracciones/solicitar_datos.jsp(9,0) 'dd/MM/yyyy'",_jsp_getExpressionFactory().createValueExpression("dd/MM/yyyy",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fparent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:parent
    org.apache.jsp.tag.web.parent_tag _jspx_th_t_005fparent_005f0 = (new org.apache.jsp.tag.web.parent_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_t_005fparent_005f0);
    _jspx_th_t_005fparent_005f0.setJspContext(_jspx_page_context);
    _jspx_th_t_005fparent_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_t_005fparent_005f0, null));
    _jspx_th_t_005fparent_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_t_005fparent_005f0);
    return false;
  }

  private boolean _jspx_meth_sf_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_sf_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    try {
      _jspx_th_sf_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005fform_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(52,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setMethod("POST");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(52,2) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setCommandName("viewModel");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(52,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setAction("/fielcorresponsal/withdraw/consultar_datos");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(52,2) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setName("myForm");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(52,2) name = onsubmit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005fform_005f0.setOnsubmit(" return validateForm()");
      int[] _jspx_push_body_count_sf_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005fform_005f0 = _jspx_th_sf_005fform_005f0.doStartTag();
        if (_jspx_eval_sf_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12  pdr-1 caja-blanca-rellena\">\n");
            out.write("\t\t\t\t<div class=\"mb-10 step-two-title\">\n");
            out.write("\t\t\t\t\t<h3>Titular de la cuenta a depositar</h3>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t<div class=\"row mb-10\">\n");
            out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\">País:</label>\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
            out.write("\t\t\t\t\t\t<select class=\"col-xs-4 col-sm-4 col-md-3 col-lg-3 input-pen-without-appearance appearance-none input-pen-tipDoc  form-control input-form-seguro\" id=\"select_client_origDoc\">\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t\t</select>\n");
            out.write("\t\t\t\t\t\t<span data-toggle=\"tooltip\" title=\"Cambiar Pais.\" class=\"icon-pencil select-btn-pen\" id=\"client_origDoc\" style=\"font-size: 100%;margin-left: 0px; margin-right: 0px;}\"></span>\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f0(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t</div>\t\t\t\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\">Nro. documento:</label>\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
            out.write("\t\t\t\t\t\t ");
            if (_jspx_meth_sf_005finput_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write(" \n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t\t<div class=\"row mb-10\">\n");
            out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\">Tipo Documento:</label>\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
            out.write("\t\t\t\t\t\t<select class=\"col-xs-4 col-sm-4 col-md-3 col-lg-3 input-pen-without-appearance appearance-none input-pen-tipDoc  form-control input-form-seguro\" id=\"select_client_tipeDoc\">\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t\t</select>\n");
            out.write("\t\t\t\t\t\t<span data-toggle=\"tooltip\" title=\"Cambiar tipo Documento.\" class=\"icon-pencil select-btn-pen\" id=\"client_tipeDoc\" style=\"font-size: 100%;margin-left: 0px; margin-right: 0px;}\"></span>\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_sf_005finput_005f2(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\" id=\"fechaNacimiento-label\">Fecha Nacimiento:</label>\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
            out.write("\t\t\t\t\t\t ");
            if (_jspx_meth_sf_005finput_005f3(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t\t <!-- \n");
            out.write("\t\t\t\t\t\t     <div class=\"input-group date\">\n");
            out.write("      \t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"><span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-th\"></i></span>\n");
            out.write("    \t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t  -->\n");
            out.write("\t\t\t\t\t\t  \n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t\t\n");
            out.write("\t\t\t\t<div class=\"row mb-10\">\n");
            out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\"></label>\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t\t<label class=\"col-xs-6 col-sm-6 col-md-2 col-lg-2 pdl-0 text-right label-form-seguro\" id=\"telefonoCelular-label\">Teléfono Celular:</label>\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-3 col-lg-3 pdl-0\">\n");
            out.write("\t\t\t\t\t\t ");
            if (_jspx_meth_sf_005finput_005f4(_jspx_th_sf_005fform_005f0, _jspx_page_context, _jspx_push_body_count_sf_005fform_005f0))
              return true;
            out.write(" \n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t\t\n");
            out.write("\t\t\t\t<div class=\"row mb-10\">\n");
            out.write("\n");
            out.write("\t\t\t\t\t<div class=\"col-xs-8 col-sm-6 col-md-5 col-lg-4 pull-right\">\n");
            out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn-next-blue\">Buscar</button>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_sf_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_sf_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005fform_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005fform_0026_005fonsubmit_005fname_005fmethod_005fcommandName_005faction.reuse(_jspx_th_sf_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(62,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("pais");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(62,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/extracciones/solicitar_datos.jsp(62,7) '${paises}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${paises}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(62,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("p_loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pais.codigoPais}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pais.codigoPais == viewModel.codigoPaisOrigen ? 'selected=\"selected\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pais.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(67,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setPath("codigoPaisOrigen");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(67,6) null
      _jspx_th_sf_005finput_005f0.setDynamicAttribute(null, "type", "hidden");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(67,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setId("client_origDoc_value");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(67,6) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f0.setCssErrorClass("col-xs-6 col-sm-6 col-md-3 col-lg-3 input-pen input-pen-tipDoc  form-control input-form-seguro");
      int[] _jspx_push_body_count_sf_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f0 = _jspx_th_sf_005finput_005f0.doStartTag();
        if (_jspx_th_sf_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody.reuse(_jspx_th_sf_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(72,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f1.setPath("numeroDocumento");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(72,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f1.setId("numeroDocumento");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(72,7) null
      _jspx_th_sf_005finput_005f1.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(72,7) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f1.setCssErrorClass(" form-control input-form-seguro");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(72,7) null
      _jspx_th_sf_005finput_005f1.setDynamicAttribute(null, "class", "form-control input-form-seguro");
      int[] _jspx_push_body_count_sf_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f1 = _jspx_th_sf_005finput_005f1.doStartTag();
        if (_jspx_th_sf_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(81,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("tipoDoc");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(81,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/extracciones/solicitar_datos.jsp(81,7) '${tipoDocumentos}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tipoDocumentos}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(81,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("p_loop");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoDoc.codigoTipoDoc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoDoc.codigoTipoDoc == viewModel.codigoTipoDocumento ? 'selected=\"selected\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tipoDoc.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(86,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f2.setPath("codigoTipoDocumento");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(86,6) null
      _jspx_th_sf_005finput_005f2.setDynamicAttribute(null, "type", "hidden");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(86,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f2.setId("client_tipeDoc_value");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(86,6) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f2.setCssErrorClass("col-xs-6 col-sm-6 col-md-3 col-lg-3 input-pen input-pen-tipDoc  form-control input-form-seguro");
      int[] _jspx_push_body_count_sf_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f2 = _jspx_th_sf_005finput_005f2.doStartTag();
        if (_jspx_th_sf_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fnobody.reuse(_jspx_th_sf_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(91,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f3.setPath("fechaNacimiento");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(91,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f3.setId("fechaNacimiento");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(91,7) null
      _jspx_th_sf_005finput_005f3.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(91,7) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f3.setCssErrorClass(" form-control input-form-seguro");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(91,7) null
      _jspx_th_sf_005finput_005f3.setDynamicAttribute(null, "class", "form-control input-form-seguro");
      int[] _jspx_push_body_count_sf_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f3 = _jspx_th_sf_005finput_005f3.doStartTag();
        if (_jspx_th_sf_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_sf_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_sf_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_sf_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sf:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_sf_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_sf_005finput_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sf_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sf_005fform_005f0);
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(108,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f4.setPath("telefonoCelular");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(108,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f4.setId("telefonoCelular");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(108,7) null
      _jspx_th_sf_005finput_005f4.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(108,7) name = cssErrorClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sf_005finput_005f4.setCssErrorClass(" form-control input-form-seguro");
      // /WEB-INF/views/extracciones/solicitar_datos.jsp(108,7) null
      _jspx_th_sf_005finput_005f4.setDynamicAttribute(null, "class", "form-control input-form-seguro");
      int[] _jspx_push_body_count_sf_005finput_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_sf_005finput_005f4 = _jspx_th_sf_005finput_005f4.doStartTag();
        if (_jspx_th_sf_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sf_005finput_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sf_005finput_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sf_005finput_005f4.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fsf_005finput_0026_005ftype_005fpath_005fid_005fcssErrorClass_005fclass_005fnobody.reuse(_jspx_th_sf_005finput_005f4);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdr-0\">\n");
      out.write("\t\t<div id=\"homeLeftPanel\" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdl-0\">\n");
      out.write("\t\t\t<div class=\"col-lg-12 col-lg-12 col-lg-6 col-lg-6 title-page\">\n");
      out.write("\t\t\t\t<h2>Extracciones en Efectivo</h2>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-lg-12 col-lg-12 col-lg-6 col-lg-6 content-list-icons\">\n");
      out.write("\t\t\t\t<ul class=\"icon\">\n");
      out.write("\t\t\t\t\t<li><a href=\"/fielcorresponsal/reports\" data-toggle=\"tooltip\" title=\"Reportes\"><span class=\"icon-chart-bar\" aria-hidden=\"true\" style=\"color: rgb(51, 122, 183);\"></span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" data-toggle=\"tooltip\" title=\"Imprimir\"><span class=\"icon-print\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" data-toggle=\"tooltip\" title=\"Mensajes\"><span class=\"icon-comment\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/fielcorresponsal/settings/change_password\" data-toggle=\"tooltip\" title=\"Configuración\"><span class=\"icon-cog\" aria-hidden=\"true\" style=\"color: rgb(51, 122, 183);\"></span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" data-toggle=\"tooltip\" title=\"Ayuda\"><span class=\"icon-help-circled\" aria-hidden=\"true\"></span></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0 sub-title-page\">\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-6 pdr-0\">\n");
      out.write("\t\t\t\t\t<h3 class=\"tipo-seguro\">Búsqueda de Cliente</h3>\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-6 pdr-0 pdlr-0 content-steps\">\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\">\n");
      out.write("\t\t\t\t\t<div class=\"content-icon-step content-icon-step-in\">\n");
      out.write("\t\t\t\t\t\t<span class=\"\">1</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"content-icon-step\">\n");
      out.write("\t\t\t\t\t\t<span class=\"\">2</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"content-icon-step\">\n");
      out.write("\t\t\t\t\t\t<span class=\"\">3</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\">\n");
      out.write("\t\t\t<hr class=\"line-blue\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 pdlr-0\" id=\"boxMessage\" style=\"display: none;\">\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERROR}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hasError\">\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${WARNING}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hasWarning\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
      if (_jspx_meth_sf_005fform_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\t</div>\n");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
